
name: CICD for Azure Function App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy-dev  :
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        app:
          - name: "fn-cicd-dev1"
            folder: "fn-dev1"	
          - name: "fn-cicd-dev2"
            folder: "fn-dev2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
    
      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}  

      - name: Deploy to Azure Function App
        #if: contains(github.event.head_commit.message, matrix.app.folder) # Check if commit includes folder changes
        uses: azure/functions-action@v1
        with:
          app-name: ${{ matrix.app.name }}
          package: ./${{ matrix.app.folder }}

        



