name: Deploy Template   

on:
 workflow_call:
  inputs:
    app-name:
        required: true
        type: string
    app-folder:
        required: true
        type: string
    python-version:
        required: false
        type: string
        default: "3.9"
    environment:
        required: true
        type: string    
  secrets:
    azure-credentials:
        required: true
        
jobs:
  deploy-template:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0                     
        - name: Check if folder has changes
          id: check_changes
          run: |
            if git diff --name-only HEAD~1 HEAD | grep -q "^${{ inputs.app-folder }}/"; then
              echo "Folder ${{ inputs.app-folder }} has changes."
              echo "deploy=true" >> $GITHUB_ENV
            else  
              echo "No changes in ${{ inputs.app-folder }}."
              echo "deploy=false" >> $GITHUB_ENV 
            fi   
            
        - name: Skip Deployment if No Changes
          if: env.deploy == 'false'
          run: |
           echo "No changes detected in the folder. Skipping deployment."
           exit 0          
     
        - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
          if: env.deploy == 'true'
          uses: actions/setup-python@v4
          with:
            python-version: ${{ inputs.python-version }}
    
        - name: 'Resolve Project Dependencies Using Pip'
          if: env.deploy == 'true'
          shell: bash
          run: |
            cd ${{ inputs.app-folder }}
            python -m pip install --upgrade pip
            pip install -r requirements.txt --target=".python_packages/lib/site-packages"
  
        - name: 'Login via Azure CLI'
          if: env.deploy == 'true'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.azure-credentials}}         
  
        - name: Deploy to Azure Function App
          if: env.deploy == 'true'
          uses: azure/functions-action@v1
          with:
            app-name: ${{ inputs.app-name }}
            package: ./${{ inputs.app-folder }}
            scm-do-build-during-deployment: true
            enable-oryx-build: true    